[package]
name = "serial_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
egui_plot = "0.27.2"
rfd = "0.14.1"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
serialport = "4.3.0"
